# vim:syntax=Dockerfile

FROM ubuntu:18.04
COPY . /app
RUN make /app
CMD python /app/app.py

FROM creates a layer from the ubuntu:18.04 Docker image.
COPY adds files from your Docker client’s current directory.
RUN builds your application with make.
CMD specifies what command to run within the container.

Сборка Docker файла расположенного локально: 
docker build .

Все образы: 
docker images

Все контейнеры, которые когда-то запускались:
docker ps -a

Запуск контейнера в консоли:
docker run -it 13bcb7e0ad0b

Войти в контейнер:
docker exec -it container_name /bin/sh

TEST
FROM alpine:3.13
ENV UID=991 GID=991
RUN apk update && apk add nginx
EXPOSE 80 443
CMD ["/bin/sh"]


